
services:
  mongodb7:
    build:
      context: ./mongodb7
      dockerfile: Dockerfile
    container_name: mongodb7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb-init-scripts:/docker-entrypoint-initdb.d
      - ./mongodb7/mongodb7-data-loader:/mongodb7-data-loader
      - ./data:/shared-data
    restart: unless-stopped

  mongodb8:
    build:
      context: ./mongodb8
      dockerfile: Dockerfile
    container_name: mongodb8
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb-init-scripts:/docker-entrypoint-initdb.d
      - ./mongodb8/mongodb8-data-loader:/mongodb8-data-loader
      - ./data:/shared-data
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ztbd
      POSTGRES_PASSWORD: ztbd
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgresql-init-scripts:/docker-entrypoint-initdb.d
      - ./postgresql-data-loader:/postgressql-data-loader  
      - ./data:/shared-data

  oracledb:
    image: gvenzl/oracle-free:latest
    container_name: oracledb
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle  # Default system password
    volumes:
      - ./oracle-init-scripts:/docker-entrypoint-initdb.d  # Mount SQL scripts
      - ./oracle-data-loader:/oracle-data-loader  # Mount script in dir where it won't be executed automatically
      - ./data:/shared-data
    restart: unless-stopped

volumes:
  mongodb7_data:
  mongodb8_data:
  postgres_data:
  oracledb_data:
